

deploy:
  provider: firebase
  token:
    secure: FIREBASE_TOKEN
  project: "pocketflix-external"
yarn: true
directories:
- node_modules
language: node_js
script:
- npm run build
message: "Deploy"
node_js:
  - "7"



