

before_install:
  - 'npm i -g firebase-tools'
yarn: true
directories:
- node_modules
language: node_js
script:
  - npm run build
  - firebase deploy --token= $FIREBASE_TOKEN--non- interactive
message: "Deploy"
node_js:
  - "7"



