
before_script:
- npm install
- npm run build
deploy:
  cache:
  yarn: true
  directories:
  - node_modules
  provider: firebase
  token:
    secure: FIREBASE_TOKEN
  language: node_js
  project: "pocketflix-external"
  message: "Deploy"
  node_js:
    - "7"

